kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: install-dependencies-and-build
  image: node:alpine
  commands:
  - npm install -g yarn
  - yarn
  - yarn run prod

- name: build-linux
  image: golang
  environment:
    GOOS: linux
  commands:
  - go build -o /drone/src/webserver -a -installsuffix cgo /drone/src/server/main.go

- name: dockerize
  image: plugins/docker
  settings:
    auto_tag: true
    repo: kubesmith/kubesmith-ui
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
