kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

volumes:
- name: artifacts
  temp: {}

steps:
- name: install-dependencies-and-build
  image: node:alpine
  commands:
  - npm install -g yarn
  - yarn
  - yarn run prod
  volumes:
  - name: artifacts
    path: /drone

- name: build-linux
  image: golang
  environment:
    GOOS: linux
    CGO_ENABLED: 0
  commands:
  - go build -o /drone/src/webserver /drone/src/server/main.go
  - cp /drone/src/webserver /artifacts/webserver
  volumes:
  - name: artifacts
    path: /drone

- name: dockerize
  image: plugins/docker
  settings:
    auto_tag: true
    repo: kubesmith/kubesmith-ui
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
  - name: artifacts
    path: /drone
