kind: pipeline
name: linux-amd64

workspace:
  base: /kubesmith-ui

platform:
  os: linux
  arch: amd64

volumes:
- name: data
  temp: {}

steps:
- name: install-dependencies
  image: node:alpine
  commands:
  - npm install -g yarn
  - yarn
  volumes:
  - name: data
    path: /kubesmith-ui

- name: build-linux
  image: golang
  environment:
    GOOS: linux
  commands:
  - go build -o /kubesmith-ui/webserver /kubesmith-ui/server/main.go
  volumes:
  - name: data
    path: /kubesmith-ui
