kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: install-dependencies-and-build
  image: node:alpine
  commands:
  - npm install -g yarn
  - yarn
  - yarn run prod

- name: build-linux
  image: golang
  environment:
    GOOS: linux
  commands:
  - go build -o /drone/src/webserver /drone/src/server/main.go
